### PR TITLE
Fix not showing class profiles when showing whole model

### LINKED ISSUE #1009: Show/hide all class profiles not working
Image

### PR DESCRIPTION
**Pull request by RadStr**
- Fixes #1009
- and moves the buttons to `vocabularies` tab as stated in the issue's comment
- Also found out that there is issue with #1017, since I call it internally, so I made a simple hotfix which catches the error and marked the hotfix with TODO

### CODE REVIEW

**Review by jakubklimek — APPROVED** [review]
It works, but is dangerous, as it loses all positions, and for APs, layouting still does not work.

**Comment by RadStr** [comment]
> It works, but is dangerous, as it loses all positions, and for APs, layouting still does not work.

- As for the losing of all positions, I think that it will be solved sometime in future by implementing #828 
- And for the layouting I just implemented it in another branch (it still has some issues, but those are related to different functionality), not sure if I should put it here or open separate PR after this one is merged

**Comment by jakubklimek** [comment]
@RadStr Separate please

File: applications/conceptual-model-editor/src/action/add-semantic-entities-to-visual-model.ts [hunk 1]
```diff
@@ -147,11 +147,21 @@ async function addClassesAndClassProfilesToVisualModel(
...
+        await addSemanticClassProfileToVisualModelAction(notifications, graph, classes, visualModel, diagram, entity.id, modelIdentifier, position);
+      }
+      else {
+        notifications.error("Adding node of not supported type");
+      }
     }
-    else {
-      await addSemanticClassProfileToVisualModelAction(notifications, graph, classes, visualModel, diagram, entity.id, modelIdentifier, position);
+    catch {
+      // Do nothing
```
Comment (skodapetr) [inline applications/conceptual-model-editor/src/action/add-semantic-entities-to-visual-model.ts:164]: There should probably be at least a log or something.
You should never silence an Exception.
